### ISSUE TITLE
I couldn't fix this issue 

### ISSUE THREAD

**Issue by xVoldx** [Nadji-abidi/faselHD#3]
![image](https://user-images.githubusercontent.com/62064902/147419033-36d93269-10ca-4424-a7ad-988f9243c3f6.png)

i selected 12 ep
but only downloads 11

![image](https://user-images.githubusercontent.com/62064902/147419040-02ceda85-6fc3-4e45-ba83-01aa72b17ae6.png)

**Comment by Nadji-abidi** [comment]
please install [m3u8downloader](https://github.com/josephcappadona/m3u8downloader) or any m3u8 downloader like [youtube-dl](https://github.com/ytdl-org/youtube-dl)

**Comment by Nadji-abidi** [comment]
because the 12th episodes is the last one "for last episodes don't put any value just hit enter"
